services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: marvin-qdrant
    volumes:
      - qdrant_storage:/qdrant/storage

  n8n:
    image: n8nio/n8n:latest
    container_name: marvin-n8n
    ports:
      - "6678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_RESTRICT_FILE_ACCESS_TO=/files
      - N8N_HOST=marvin-logistics.duckdns.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_WEBHOOK_URL=https://marvin-logistics.duckdns.org
      - N8N_EDITOR_BASE_URL=https://marvin-logistics.duckdns.org
      - N8N_PROXY_HOPS=1
      - N8N_SECURE_COOKIE=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./documentos/pdf:/files:ro
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
  n8n_data:
