services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: marvin-qdrant
    ports:
      - "7333:6333"
      - "7334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  n8n:
    image: n8nio/n8n:latest
    container_name: marvin-n8n
    ports:
      - "6678:5678"
    environment:
    - GENERIC_TIMEZONE=America/Sao_Paulo
    - TZ=America/Sao_Paulo
    - N8N_RESTRICT_FILE_ACCESS_TO=/files
    - N8N_HOST=localhost
    - N8N_PORT=5678
    - N8N_PROTOCOL=http
    - N8N_WEBHOOK_URL=http://localhost:6678/
    - N8N_EDITOR_BASE_URL=http://localhost:6678/
    - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./documentos/pdf:/files:ro
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
  n8n_data: